apiVersion: v1
kind: ConfigMap
metadata:
  name: inpt-ride-config
  namespace: inpt-ride
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend,inpt-ride-backend"

  POSTGRES_DB: "inpt_ride_db"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  GOOGLE_WEB_CLIENT_ID: "k8s-placeholder"