apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  namespace: inpt-ride
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: backend-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: nadaaath/inpt-ride-backend:latest
          imagePullPolicy: Always
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: inpt-ride-config
            - secretRef:
                name: inpt-ride-secret