apiVersion: v1
kind: Secret
metadata:
  name: inpt-ride-secret
  namespace: inpt-ride
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "change-this-k8s-secret-key"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"