apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inpt-ride
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  project: default
  source:
    repoURL: https://github.com/Nadaaath/INPT-Ride.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: inpt-ride
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true